INSERT INTO BRAND(NAME) VALUES ('HIGH');
INSERT INTO BRAND(NAME) VALUES ('Thrasher');
INSERT INTO BRAND(NAME) VALUES ('Diamond');

INSERT INTO PRODUCT(NAME,DESCRIPTION,BRAND_ID, PRICE) VALUES ('Moletom HIGH Kidz', 'Moletom CANGURU modelo Kidz', 1, 10.00);
INSERT INTO PRODUCT(NAME,DESCRIPTION,BRAND_ID, PRICE) VALUES ('Aoletom HIGH Kidz', 'Moletom CANGURU modelo Kidz', 1, 10.00);
 
INSERT INTO USER(NAME,EMAIL,PASSWORD) VALUES ('teste','teste','$2a$10$cBP1lgGrZv9mklgsj0Fof.vnI5iHFG/35z9iWgFgha6Da.GPq11Py');