INSERT INTO BRAND(NAME) VALUES ('HIGH');
INSERT INTO BRAND(NAME) VALUES ('Thrasher');
INSERT INTO BRAND(NAME) VALUES ('Diamond');

INSERT INTO PRODUCT(NAME,DESCRIPTION,BRAND_ID, PRICE) VALUES ('Moletom HIGH Kidz', 'Moletom CANGURU modelo Kidz', 1, 10.00);